<select class="tour-lang-select notranslate" aria-label="Select Language">
    <option value="">Select Language</option>
    <option value="auto|af" data-gt-href="#">Afrikaans</option>
    <option value="auto|sq" data-gt-href="#">Albanian</option>
    <option value="auto|am" data-gt-href="#">Amharic</option>
    <option value="auto|ar" data-gt-href="#">Arabic</option>
    <option value="auto|hy" data-gt-href="#">Armenian</option>
    <option value="auto|az" data-gt-href="#">Azerbaijani</option>
    <option value="auto|eu" data-gt-href="#">Basque</option>
    <option value="auto|be" data-gt-href="#">Belarusian</option>
    <option value="auto|bn" data-gt-href="#">Bengali</option>
    <option value="auto|bs" data-gt-href="#">Bosnian</option>
    <option value="auto|bg" data-gt-href="#">Bulgarian</option>
    <option value="auto|ca" data-gt-href="#">Catalan</option>
    <option value="auto|ceb" data-gt-href="#">Cebuano</option>
    <option value="auto|ny" data-gt-href="#">Chichewa</option>
    <option value="auto|zh-CN" data-gt-href="#">Chinese (Simplified)</option>
    <option value="auto|zh-TW" data-gt-href="#">Chinese (Traditional)</option>
    <option value="auto|co" data-gt-href="#">Corsican</option>
    <option value="auto|hr" data-gt-href="#">Croatian</option>
    <option value="auto|cs" data-gt-href="#">Czech</option>
    <option value="auto|da" data-gt-href="#">Danish</option>
    <option value="auto|nl" data-gt-href="#">Dutch</option>
    <option value="auto|en" data-gt-href="#" selected="">English</option>
    <option value="auto|eo" data-gt-href="#">Esperanto</option>
    <option value="auto|et" data-gt-href="#">Estonian</option>
    <option value="auto|tl" data-gt-href="#">Filipino</option>
    <option value="auto|fi" data-gt-href="#">Finnish</option>
    <option value="auto|fr" data-gt-href="#">French</option>
    <option value="auto|fy" data-gt-href="#">Frisian</option>
    <option value="auto|gl" data-gt-href="#">Galician</option>
    <option value="auto|ka" data-gt-href="#">Georgian</option>
    <option value="auto|de" data-gt-href="#">German</option>
    <option value="auto|el" data-gt-href="#">Greek</option>
    <option value="auto|gu" data-gt-href="#">Gujarati</option>
    <option value="auto|ht" data-gt-href="#">Haitian Creole</option>
    <option value="auto|ha" data-gt-href="#">Hausa</option>
    <option value="auto|haw" data-gt-href="#">Hawaiian</option>
    <option value="auto|iw" data-gt-href="#">Hebrew</option>
    <option value="auto|hi" data-gt-href="#">Hindi</option>
    <option value="auto|hmn" data-gt-href="#">Hmong</option>
    <option value="auto|hu" data-gt-href="#">Hungarian</option>
    <option value="auto|is" data-gt-href="#">Icelandic</option>
    <option value="auto|ig" data-gt-href="#">Igbo</option>
    <option value="auto|id" data-gt-href="#">Indonesian</option>
    <option value="auto|ga" data-gt-href="#">Irish</option>
    <option value="auto|it" data-gt-href="#">Italian</option>
    <option value="auto|ja" data-gt-href="#">Japanese</option>
    <option value="auto|jw" data-gt-href="#">Javanese</option>
    <option value="auto|kn" data-gt-href="#">Kannada</option>
    <option value="auto|kk" data-gt-href="#">Kazakh</option>
    <option value="auto|km" data-gt-href="#">Khmer</option>
    <option value="auto|ko" data-gt-href="#">Korean</option>
    <option value="auto|ku" data-gt-href="#">Kurdish (Kurmanji)</option>
    <option value="auto|ky" data-gt-href="#">Kyrgyz</option>
    <option value="auto|lo" data-gt-href="#">Lao</option>
    <option value="auto|la" data-gt-href="#">Latin</option>
    <option value="auto|lv" data-gt-href="#">Latvian</option>
    <option value="auto|lt" data-gt-href="#">Lithuanian</option>
    <option value="auto|lb" data-gt-href="#">Luxembourgish</option>
    <option value="auto|mk" data-gt-href="#">Macedonian</option>
    <option value="auto|mg" data-gt-href="#">Malagasy</option>
    <option value="auto|ms" data-gt-href="#">Malay</option>
    <option value="auto|ml" data-gt-href="#">Malayalam</option>
    <option value="auto|mt" data-gt-href="#">Maltese</option>
    <option value="auto|mi" data-gt-href="#">Maori</option>
    <option value="auto|mr" data-gt-href="#">Marathi</option>
    <option value="auto|mn" data-gt-href="#">Mongolian</option>
    <option value="auto|my" data-gt-href="#">Myanmar (Burmese)</option>
    <option value="auto|ne" data-gt-href="#">Nepali</option>
    <option value="auto|no" data-gt-href="#">Norwegian</option>
    <option value="auto|ps" data-gt-href="#">Pashto</option>
    <option value="auto|fa" data-gt-href="#">Persian</option>
    <option value="auto|pl" data-gt-href="#">Polish</option>
    <option value="auto|pt" data-gt-href="#">Portuguese</option>
    <option value="auto|pa" data-gt-href="#">Punjabi</option>
    <option value="auto|ro" data-gt-href="#">Romanian</option>
    <option value="auto|ru" data-gt-href="#">Russian</option>
    <option value="auto|sm" data-gt-href="#">Samoan</option>
    <option value="auto|gd" data-gt-href="#">Scottish Gaelic</option>
    <option value="auto|sr" data-gt-href="#">Serbian</option>
    <option value="auto|st" data-gt-href="#">Sesotho</option>
    <option value="auto|sn" data-gt-href="#">Shona</option>
    <option value="auto|sd" data-gt-href="#">Sindhi</option>
    <option value="auto|si" data-gt-href="#">Sinhala</option>
    <option value="auto|sk" data-gt-href="#">Slovak</option>
    <option value="auto|sl" data-gt-href="#">Slovenian</option>
    <option value="auto|so" data-gt-href="#">Somali</option>
    <option value="auto|es" data-gt-href="#">Spanish</option>
    <option value="auto|su" data-gt-href="#">Sundanese</option>
    <option value="auto|sw" data-gt-href="#">Swahili</option>
    <option value="auto|sv" data-gt-href="#">Swedish</option>
    <option value="auto|tg" data-gt-href="#">Tajik</option>
    <option value="auto|ta" data-gt-href="#">Tamil</option>
    <option value="auto|te" data-gt-href="#">Telugu</option>
    <option value="auto|th" data-gt-href="#">Thai</option>
    <option value="auto|tr" data-gt-href="#">Turkish</option>
    <option value="auto|uk" data-gt-href="#">Ukrainian</option>
    <option value="auto|ur" data-gt-href="#">Urdu</option>
    <option value="auto|uz" data-gt-href="#">Uzbek</option>
    <option value="auto|vi" data-gt-href="#">Vietnamese</option>
    <option value="auto|cy" data-gt-href="#">Welsh</option>
    <option value="auto|xh" data-gt-href="#">Xhosa</option>
    <option value="auto|yi" data-gt-href="#">Yiddish</option>
    <option value="auto|yo" data-gt-href="#">Yoruba</option>
    <option value="auto|zu" data-gt-href="#">Zulu</option>
</select>
